[package]
name = "fair-launch-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.fair-launch]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.5"
default-features = false
