[package]
name = "kitty-ownership-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.kitty-ownership]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
