[package]
name = "liquid-locking-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.liquid-locking]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
