[package]
name = "erc3643-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.erc3643]
path = ".."

[dependencies.dharitri-sc-meta]
version = "=0.13.9"
default-features = false
