[package]
name = "on-chain-claim-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Vlad Bucur <vlad.bucur@dharitri.com>"]

[dev-dependencies]

[dependencies.on-chain-claim]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.9"
default-features = false
