[package]
name = "dn404-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.dn404]
path = ".."

[dependencies.dharitri-sc-meta]
version = "=0.13.9"
default-features = false
